### ISSUE TITLE
Missing check_calibration.launch

### ISSUE THREAD

**Issue by nlimpert** [marcoesposito1988/easy_handeye_demo#3]
According to [this line](https://github.com/marcoesposito1988/easy_handeye_demo/blame/0abb19ac3ad72c44dc49e4a763baa7b64cb10509/README.md#L6) there should be a `check_calibration.launch` which seems to have never made it into this repository.

**Comment by marcoesposito1988** [comment]
You are totally right, I am still working on it.

In the meantime, you can manually inspect the result that you get after pressing the "compute" button with the value of the `calibration_transform` parameter in `calibrate.launch` (according to `eye_on_hand`)

**Comment by nlimpert** [comment]
Closing due to fix in commit 0d5faae8923f9b0959b3b292ca3c54372bdad51a.
