### ISSUE TITLE
calibration.launch file bug?

### ISSUE THREAD

**Issue by hsnuhayato** [marcoesposito1988/easy_handeye_demo#4]
hi
I think the line
https://github.com/marcoesposito1988/easy_handeye_demo/blob/0abb19ac3ad72c44dc49e4a763baa7b64cb10509/launch/calibrate.launch#L35
should be 
```xml
 <arg name="eye_on_hand" value="$(arg eye_on_hand)" />
```
doesn't it?

**Comment by marcoesposito1988** [comment]
Yes, good catch. Thanks!
