### ISSUE TITLE
the simulation starting command miss <launch_file>.launch in README.md

### ISSUE THREAD

**Issue by lyh458** [marcoesposito1988/easy_handeye_demo#5]
Hi, is that the command 

```
roslaunch easy_handeye_demo eye_on_hand:=true
```

in [README.md#getting-started*start the simulation](https://github.com/marcoesposito1988/easy_handeye_demo#getting-started)
should be

```
roslaunch easy_handeye_demo calibration.launch eye_on_hand:=true
```

? Because **easy_handeye_demo** is the package name and **eye_on_hand** is a arg, missing a launch file, which will cause a error:

``` error
RLException: [easy_handeye_demo] is not a launch file name
The traceback for the exception was written to the log file
```

**Comment by marcoesposito1988** [comment]
Yes, you're absolutely right.. thanks a lot!
